ks1 = int(input('Digite Algo: '))
classe = (type(ks1))
print(f'A classe primitiva é {classe}')
print(f'{ks1} é numerico')
print(ks1.isnumeric())
print(f'{ks1} é Alfabetico')
print(ks1.isalpha())
print(f'{ks1} é alfanumerico')
print(ks1.isalnum())
